# fly.toml app configuration file generated for my-capstone-project on 2025-11-07T20:52:59+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-capstone-project'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

# Health checks tell Fly.io when your app is ready to receive traffic.
[[http_service.checks]]
  interval = "10s"
    # The grace period is the time to wait after a machine starts before
    # health checks are considered failed.
    grace_period = "60s"
  timeout = "2s"
  method = "GET"
  # This path should match the health check endpoint in your main.py
  path = "/api/v1/health"
