# render.yaml
# This file defines the services for your application on Render.

services:
  - type: web
    name: meb-school-backend # You can name this whatever you like
    env: docker
    repo: https://github.com/eddygreat/Meb_School_Management_system # Your repo URL
    branch: main # Or your deployment branch
    dockerfilePath: ./Dockerfile
    
    # This command runs after a new build, but before the new version is deployed.
    # It's the perfect place for database migrations.
    preDeploy:
      command: "alembic upgrade head"

    # You can also define your environment variables here
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-render-database-name # The name of your Render Postgres instance
          property: connectionString
      - key: SECRET_KEY
        generateValue: true # Render can generate a secure secret for you